script: bash ./deploy.sh
language: node_js
node_js:
- '5.0'
env:
  global:
  - GH_REF: github.com/koodiklinikka/koodiklinikka.github.io.git
  - secure: "FJrEWT12tLNg2NCEtbaBYy67suaMQgkK0TDBgThNXuzQJKrlhndJ4xvb4MEH506D7fuxHl7oVXB59MxxFdX9G63t9wf3tktA57vAYV4jMndhDnp2R6fPfSMNrNwoFmJs6lis09N+iJWlIPJD3wdmzoimnGyRuYxT2rLe6iCMbLEafElmL4hSNNDmbkJM53LqXmbbTmsBVuwnh5b6DbHaMrk9QIefUlmjrEXF+ZYuAAvw+HI/Gr5cAIdgi+v6wJ7zPfJVAjX0WDjVeQ0xTJy4LXV4KwohY8mX/IF+JiS8CmEbTE0wMPCpZoTiPfdtQcDeCtkbsrJeo6LkzPmUmQPkQ9t4DdO4OVsSWjJiaodQCbJXnfAR9RZKCtFSolq4FVzc9XRAMtZBKqQlkkEZIxWNQhZgFxi8GDY3wRF3FjgFrmVK1gbw+MU+35GtCZNL+IrXGnL2drZVJ2V3dvdXq8C+yIAUebFFhxuzyoTay2dL8L/xGvOTibBE2AH3Gna+YHx8ObdWCJnRLutUVPQllj52Acr4chAfk/wz8BVwiTMaTvk3PXHCh/AjLMEa+bInnqx52QMRimhMPg6cdookUfie78uuCpGGnOuDIiFByMOKYVPQD7FhyXxV0uFQfEYdbR14GJM70m1cBQQ+kgFpQ9gaHaW6DOo9jgFflaf1pwFuou8="
