script: bash ./deploy.sh
language: node_js
node_js:
- '5.0'
env:
  global:
  - GH_REF: github.com/koodiklinikka/koodiklinikka.github.io.git
  - secure: "CViMyYB/e/1LPC5Jn44w7Za+boSrs+gProdeceMymTylADqpm8iJhIWqYfGOKkfpMor2dj9N31tWgMsI71R5l2xBV5Ne7RnCu9HT6vYnF4wnKzOeaQtCn003pZAFPK9Nk3xTR2rAIAHIkcZ6WBtu3L0j9dbUclkubPmvec3nDpnFNiWOJMQuYttxH4aNGctb/CaL7T90rLHR97KWf0i9PWJUzI68qIoUzzGeCx+reZ5XC1+HRI22FbN0Zs8jNOobNXapqTOS7x5gY3JW6e1RXRtQKfuuaRCOXO4aSxCSJ7/I0Rc0c+nmpKmzpJVrJ7i9dDWCcYfvlsJjZ/PbUZ34iobPNah0JsD7z7dvm3MbJ8ML2vsYFrm4b5EaBU2Buq1rTfnZZktHvw9VirhJA94v3AoE/FqZPgjgoI1jp2y41GdRBIuj3PjcSKwi6Xj4wsPOKqNfHvb7+CezgVAckkwIrOhgnjGdot4uvInAQCFoCAPzsGhAPNFIs8cJX60jZpwuJ1jvEVsWmUK4jNt/12FaeUIkiAUtxASOxMkQadmEEtgGYwCaCW7TS6CxPq2TMOdVkY0CFpK/S+n74K4tqQMa+uSreSqNU1Cy2TWZooeFR9xJ0IAX7agIoI06RqMNaqiYXJeA1cZOPffWmM54vjk8pWQ+P0i9iSNFjnvtW2suKgs="
